# Import lib

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import skfuzzy as fuzz
import random
import os
import cv2 as cv2
import numpy as np
import math as math
import time
from sklearn.metrics.pairwise import euclidean_distances

C = 5
D = 3
M = 2.5
error = 0.1
maxiter = 1000



In [7]:
img = cv2.imread('2.png')
N = img.shape[0] * img.shape[1]
X = img.reshape(N, 3)
V = np.random.rand(C, D)
U = np.ndarray(shape=(N, C))

print(X)
print(V)
print(img.shape[0], img.shape[1], img.shape[2])

[[179 179 179]
 [179 179 179]
 [178 178 178]
 ...
 [127 127 127]
 [129 129 129]
 [130 130 130]]
[[0.95013957 0.63283613 0.1737992 ]
 [0.14834791 0.20558438 0.5720236 ]
 [0.44116917 0.76614301 0.97068601]
 [0.72099226 0.80528243 0.05608149]
 [0.30322909 0.07658103 0.17582756]]
200 200 3


In [8]:
def initU(U):
    
    p = 2.0/(M-1)
    
    for i in range(N):
        distances = [euclidean_distances(X[i].reshape(1,-1), V[j].reshape(1,-1)) for j in range(C)]
        for j in range(C):
            denom = sum([math.pow((distances[j]/distances[k]), p) for k in range(C)])
            U[i][j] = 1.0/denom
     

def normalizeU(U):
    
    for i in range(N):
        sigma = sum(U[i])
        U[i] = [u/sigma for u in U[i]]
    

def updateV():
    
    U_zipped = zip(*U)
    V = list()
    
    for j in range(C):
        
        U_col = list(U_zipped)
        u_exp = [u ** m for u in U_col]
        denom = sum(u_exp)
        temp_num = list()
        
        for i in range(N):
            
         
            

def updateU():
    
    
        
        
    
    
    
        
    
def fuzzyCMeans(X, C, M, error, maxiter):
    
    initU(U)
    normalizeU(U)
    
    while True: 
        
        updateV()
        U_old = U.copy()
        updateU()
        
        if(maxDiffU(U - U_old) < error):
            break
    
    
    return V, U
    

In [9]:
fuzzyCMeans(X, C, M, error, maxiter)

[[0.20017736 0.19976409 0.20038782 0.20009037 0.19958036]
 [0.20017736 0.19976409 0.20038782 0.20009037 0.19958036]
 [0.20017836 0.19976276 0.20039001 0.20009088 0.19957799]
 ...
 [0.20025001 0.19966713 0.2005474  0.20012719 0.19940826]
 [0.20024613 0.19967231 0.20053888 0.20012523 0.19941745]
 [0.20024424 0.19967484 0.20053471 0.20012427 0.19942194]]
[[0.20017736 0.19976409 0.20038782 0.20009037 0.19958036]
 [0.20017736 0.19976409 0.20038782 0.20009037 0.19958036]
 [0.20017836 0.19976276 0.20039001 0.20009088 0.19957799]
 ...
 [0.20025001 0.19966713 0.2005474  0.20012719 0.19940826]
 [0.20024613 0.19967231 0.20053888 0.20012523 0.19941745]
 [0.20024424 0.19967484 0.20053471 0.20012427 0.19942194]]


In [30]:
a = [1,2,3]
b = ['m', 'n', 'p']

c = [(1,'a'), (2, 'b'), (3, 'c')]

d, e = zip(*c)
print (d,e)

(1, 2, 3) ('a', 'b', 'c')
